// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQGX0auFmyw5AxLNebtM9muPCtjGkCGyw',
    appId: '1:206873749930:web:c45051c20ca039c5d7e3d3',
    messagingSenderId: '206873749930',
    projectId: 'campus-connect-1029',
    authDomain: 'campus-connect-1029.firebaseapp.com',
    storageBucket: 'campus-connect-1029.firebasestorage.app',
    measurementId: 'G-8RYMFJTBRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAQoIT4VPGTeAQhTIVQtVR0YP_ToMna7U',
    appId: '1:206873749930:android:ba428d3bb6dfb5a9d7e3d3',
    messagingSenderId: '206873749930',
    projectId: 'campus-connect-1029',
    storageBucket: 'campus-connect-1029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46vtWovbKcNFR-TPnZafW12eWRTm6sFw',
    appId: '1:206873749930:ios:7e97e3ef6c08ec24d7e3d3',
    messagingSenderId: '206873749930',
    projectId: 'campus-connect-1029',
    storageBucket: 'campus-connect-1029.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA46vtWovbKcNFR-TPnZafW12eWRTm6sFw',
    appId: '1:206873749930:ios:7e97e3ef6c08ec24d7e3d3',
    messagingSenderId: '206873749930',
    projectId: 'campus-connect-1029',
    storageBucket: 'campus-connect-1029.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQGX0auFmyw5AxLNebtM9muPCtjGkCGyw',
    appId: '1:206873749930:web:5883dc13b881bc29d7e3d3',
    messagingSenderId: '206873749930',
    projectId: 'campus-connect-1029',
    authDomain: 'campus-connect-1029.firebaseapp.com',
    storageBucket: 'campus-connect-1029.firebasestorage.app',
    measurementId: 'G-FDP1N8NZ7W',
  );
}
